import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'labelito',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} dark:bg-gray-900 dark:text-white`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
